Allowed filtering of ended arrangements
CareTogether/CareTogetherCMS pull request #662
Opened 2023-06-21 04:39 UTC by jaysengardner

2023-07-14 19:38 UTC, LarsKemmann requested changes
A decent start but needs some more work and testing.

2023-07-14 19:38 UTC, LarsKemmann commented on src/caretogether-pwa/src/Families/FamilyScreen.tsx
> +      }
Please make sure that the whitespace/indentation levels are aligned correctly.

2023-07-14 19:38 UTC, LarsKemmann commented on src/caretogether-pwa/src/Families/FamilyScreen.tsx
> +			} else if (opt === ArrangementFilterOptionLabel.Ended && arrangement.cancelledAtUtc !== undefined) {
```suggestion
			} else if (opt === ArrangementFilterOptionLabel.Ended && arrangement.endedAtUtc !== undefined) {
```
I think the original code you wrote has a logic bug in it? Take a look at this proposed edit and see if that's the case. Either way, when you know it's correct, include a screenshot or two in your PR showing the correct logic with some sample data that you've entered to demonstrate that you've tested it.

2023-07-22 00:33 UTC, jaysengardner commented
Fixed a logic error that was present in my original code. Images provided to show that it is now working as intended.

2023-07-22 00:36 UTC, jaysengardner commented
![Screenshot (1)](https://github.com/CareTogether/CareTogetherCMS/assets/40499684/15e96657-36f8-48f7-890c-413bed4eecc4)

2023-07-22 00:36 UTC, jaysengardner commented
![Screenshot (2)](https://github.com/CareTogether/CareTogetherCMS/assets/40499684/b784dd11-4af6-4865-b4ea-a240b6ec84ae)

2023-07-24 18:23 UTC, LarsKemmann commented
> Fixed a logic error that was present in my original code. Images provided to show that it is now working as intended.

I don't see an ended arrangement in your screenshots, nor any indication of what you set the filter options to.

2023-07-28 12:28 UTC, LarsKemmann approved these changes
Looks great, thank you!!

2023-07-28 12:31 UTC, merged