Change h3 to typography
CareTogether/CareTogetherCMS pull request #766
Opened 2024-08-05 21:54 UTC by Rabi94

I changed all the h3 elements to Typography components with variant="h3" and set the font size to 2rem to maintain the original font size.

2024-08-28 16:40 UTC, LarsKemmann requested changes
The change to `<Typography>` is good, and we want to use the `h3` variant. But, the font size is too big and we don't want to set it everywhere. Please set it in the global Material UI theme settings, and match (roughly) the font size for `h6`.

2024-08-28 16:44 UTC, LarsKemmann commented
https://v5.mui.com/material-ui/customization/theming/
https://v5.mui.com/material-ui/customization/typography/

2024-08-30 14:09 UTC, PabloDinella requested changes

2024-08-30 14:09 UTC, PabloDinella commented on src/caretogether-pwa/src/theme.tsx
> +        [createTheme().breakpoints.up('sm')]: {
I think you forgot to remove the line 17, as both 17 and 18 do the same thing

2024-08-30 16:06 UTC, LarsKemmann approved these changes
Looks great @Rabi94 and @PabloDinella - thank you!

2024-08-30 16:06 UTC, PabloDinella approved these changes

2024-08-30 16:07 UTC, LarsKemmann approved these changes

2024-08-30 16:08 UTC, LarsKemmann approved these changes

2024-08-30 16:08 UTC, merged